// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAhIqqX4ZqheTo0Vd1u7FXaQDjKtN0qhY',
    appId: '1:330324088156:web:7ca7b8f2da150494951d99',
    messagingSenderId: '330324088156',
    projectId: 'gakusai-6c962',
    authDomain: 'gakusai-6c962.firebaseapp.com',
    storageBucket: 'gakusai-6c962.firebasestorage.app',
    measurementId: 'G-8D17RD771L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuFR1RFJAocdnKUQ_h2cVrCbl3oXgwu_k',
    appId: '1:330324088156:android:5498af107b4fccc3951d99',
    messagingSenderId: '330324088156',
    projectId: 'gakusai-6c962',
    storageBucket: 'gakusai-6c962.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo3Css2Ri04DWENuDYLE1pbpldiHXk2iQ',
    appId: '1:330324088156:ios:1f6ab2d45dda4108951d99',
    messagingSenderId: '330324088156',
    projectId: 'gakusai-6c962',
    storageBucket: 'gakusai-6c962.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo3Css2Ri04DWENuDYLE1pbpldiHXk2iQ',
    appId: '1:330324088156:ios:1f6ab2d45dda4108951d99',
    messagingSenderId: '330324088156',
    projectId: 'gakusai-6c962',
    storageBucket: 'gakusai-6c962.firebasestorage.app',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAhIqqX4ZqheTo0Vd1u7FXaQDjKtN0qhY',
    appId: '1:330324088156:web:3d1dfef902a9545e951d99',
    messagingSenderId: '330324088156',
    projectId: 'gakusai-6c962',
    authDomain: 'gakusai-6c962.firebaseapp.com',
    storageBucket: 'gakusai-6c962.firebasestorage.app',
    measurementId: 'G-TNR29R686J',
  );
}
